directories:
  output: dist_electron
  buildResources: assets
appId: com.metastation.app
productName: MetaStation
asar: true
asarUnpack:
  - dist
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target:
    - nsis
    - portable
  icon: assets/logo.ico
nsis:
  oneClick: false
  perMachine: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: MetaStation
  uninstallDisplayName: MetaStation
  artifactName: MetaStation-Setup-${version}.exe
electronVersion: 38.1.2
